[database]
url = "postgres://ign:test@localhost:5432/ign"
url_nossl = "postgres://ign:test@localhost:5432/ign?sslmode=disable"
port = 40001

[general]
version = "1.0.0"

[secret]
symmetric_key = "7dbbcee180ba4d456e4aa1cfbdad9c7b"